# Generated by Django 2.1.5 on 2019-07-30 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('methodmapping', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('secret_key', models.CharField(editable=False, max_length=32)),
                ('methods', models.ManyToManyField(to='methodmapping.MethodMapping')),
            ],
            options={
                'verbose_name': 'User and Secret Key',
                'verbose_name_plural': 'Users and Secret Keys',
            },
        ),
    ]
