# Generated by Django 2.1.5 on 2019-03-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodmapping', '0001_initial'),
        ('secret', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secret',
            options={'verbose_name': 'User and Secret Key', 'verbose_name_plural': 'Users and Secret Keys'},
        ),
        migrations.AddField(
            model_name='secret',
            name='methods',
            field=models.ManyToManyField(to='methodmapping.MethodMapping'),
        ),
        migrations.AlterField(
            model_name='secret',
            name='secret_key',
            field=models.CharField(editable=False, max_length=32),
        ),
        migrations.AlterField(
            model_name='secret',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
