# Generated by Django 2.1.5 on 2019-04-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0002_auto_20190318_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='fullname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
