# Generated by Django 2.1.5 on 2019-03-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('secret', '0002_auto_20190313_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
                ('uri', models.CharField(max_length=255)),
                ('secrets', models.ManyToManyField(to='secret.Secret')),
            ],
        ),
    ]
