# Generated by Django 2.1.5 on 2019-07-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MethodMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
                ('uri', models.CharField(help_text='Exemplo: /user/mpmapas/staging/datalake/cpf', max_length=255)),
                ('description', models.TextField()),
                ('mandatory_headers', models.TextField(blank=True)),
            ],
        ),
    ]
