# Generated by Django 2.1.5 on 2020-04-28 12:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations

from methodmapping.helpers import header_to_schema


def reverse_func(apps, schema_editor):
    pass


def populate_schema(apps, schema_editor):
    MethodMapping = apps.get_model("methodmapping", "MethodMapping")
    for method in MethodMapping.objects.all():
        if method.mandatory_headers == "":
            schema = None
        else:
            schema = header_to_schema(method.mandatory_headers)

        method.schema=schema
        method.save()


class Migration(migrations.Migration):

    dependencies = [
        ('methodmapping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodmapping',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.RunPython(populate_schema, reverse_func),
        migrations.RemoveField(
            model_name="methodmapping",
            name="mandatory_headers",
        )
    ]
