# Generated by Django 2.1.5 on 2019-04-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodmapping', '0002_methodmapping_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodmapping',
            name='mandatory_headers',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
