# Generated by Django 2.1.5 on 2019-05-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodmapping', '0003_methodmapping_mandatory_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodmapping',
            name='mandatory_headers',
            field=models.TextField(blank=True),
        ),
    ]
